# Generated by Django 3.1 on 2020-11-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201101_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='mark',
        ),
    ]
