# Generated by Django 3.1 on 2020-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201106_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_info',
            name='course_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
