# Generated by Django 3.1 on 2020-11-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_student_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='q_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
