# Generated by Django 3.1 on 2020-11-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_exams_q_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='q_number',
        ),
    ]
