# Generated by Django 3.1 on 2020-10-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_info',
            name='lecture_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='student_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
