# Generated by Django 3.1 on 2020-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201019_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='face_image',
            field=models.BinaryField(max_length=65535),
        ),
    ]
