# Generated by Django 3.1 on 2020-10-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201022_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='face_image',
        ),
    ]
