# Generated by Django 3.1 on 2020-10-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_info_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='mark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exams',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exams',
            name='test_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitted',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitted',
            name='exam_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitted',
            name='examiner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitted',
            name='module',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitted',
            name='n_s',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitted',
            name='student_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test_info',
            name='examiner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test_info',
            name='mark_tot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test_info',
            name='module',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test_info',
            name='test_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test_info',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin_info',
            name='lecture_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exams',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='student_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submitted',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
