# Generated by Django 3.1 on 2020-10-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_courses_subject_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
