# Generated by Django 3.1 on 2020-11-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_courses_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_info',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='test_info',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test_info',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
