# Generated by Django 3.1 on 2020-11-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_exams_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='course_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='student_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
