# Generated by Django 3.1 on 2020-11-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_student_info_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
