# Generated by Django 3.1 on 2020-11-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_exams_q_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitted',
            name='examiner',
        ),
        migrations.RemoveField(
            model_name='submitted',
            name='module',
        ),
        migrations.RemoveField(
            model_name='submitted',
            name='n_s',
        ),
        migrations.AddField(
            model_name='submitted',
            name='paper',
            field=models.FileField(null=True, upload_to='submitted/pdfs'),
        ),
        migrations.AddField(
            model_name='submitted',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submitted',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
